use crate::controller::*;
use actix_web::web;

pub fn config_services(cfg: &mut web::ServiceConfig) {
    info!("Configurating routes...");
    cfg.service(
        web::scope("/api")
            .service(ping_controller::ping)
            .service(
                web::scope("/auth")
                    .service(
                        web::resource("/signup")
                            .route(web::post().to(account_controller::signup))
                    )
                    .service(
                        web::resource("/login")
                            .route(web::post().to(account_controller::login))
                    )
            )
            .service(
                web::scope("/app-users")
                    .service(
                        web::resource("")
                            .route(web::post().to(app_user_controller::create))
                    )
                    .service(
                        web::resource("/online/{app_id}")
                            .route(web::get().to(app_user_controller::online_users))
                    )
                    .service(
                        web::resource("/{app_id}")
                            .route(web::get().to(app_user_controller::find_by_app_id))
                    )
            )
            .service(
                web::scope("/chat-rooms")
                    .service(
                        web::resource("")
                            .route(web::post().to(chat_room_controller::create_room))
                    )
                    .service(
                        web::resource("")
                            .route(web::delete().to(chat_room_controller::delete))
                    )
                    .service(
                        web::resource("/add-user")
                            .route(web::post().to(chat_room_controller::add_room_user))
                    )
                    .service(
                        web::resource("/list/{app_id}")
                            .route(web::get().to(chat_room_controller::find_by_app_id))
                    )
                    .service(
                        web::resource("/list/{app_id}/{user_id}")
                            .route(web::get().to(chat_room_controller::find_by_user_id))
                    )
                    .service(
                        web::resource("/list/{app_id}/{user_id}/{room_type}")
                            .route(web::get().to(chat_room_controller::find_by_room_type))
                    )
                    .service(
                        web::resource("/unread-count/{app_id}/{room_id}/{user_id}")
                            .route(web::get().to(chat_room_controller::update_unread_count))
                    )
            )
            .service(
                web::scope("/messages")
                    .service(
                        web::resource("")
                            .route(web::post().to(message_controller::add))
                    )
                    .service(
                        web::resource("")
                            .route(web::delete().to(message_controller::delete))
                    )
                    .service(
                        web::resource("/{room_id}")
                            .route(web::get().to(message_controller::find_by_room_id))
                    )
            )
    );
}